services:
  web:
    build:
      context: ./dundie-next-app
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
    stdin_open: true
    tty: true

  api:
    build:
      context: ./dundie-api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      DUNDIE_DB__uri: "postgresql://postgres:postgres@db:5432/${DUNDIE_DB:-dundie}"
      DUNDIE_DB__connect_args: "{}"
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    build: ./dundie-api/postgres
    image: dundie_postgres-13-alpine-multi-user
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DBS=dundie, dundie_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres